### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by iamchriswick** [Bipsync/VagrantBar#10]
Where do I set the configurations?

**Comment by Adeynack** [comment]
Suggestions for potential configuration screen:

- The flat icon. It's at the moment configurable via terminal, but it would be a nice check box to have in a preferences screen. When the icon is flat, the number beside it is not. Meaning that on Yosemite black menu bar, we do not see it at all.

- The terminal to use when launching SSH. ie: I am using iTerm2 and I would prefer it to be used over OS X's Terminal application.

- [ Aliasing / bypassing the name ] of our VMs for quick reference in the list.

**Comment by johnjamesjacoby** [comment]
Confirming that Yosemite's black menu bar is not a great experience:
![screen shot 2015-05-14 at 11 20 26 am](https://cloud.githubusercontent.com/assets/88951/7636196/43312744-fa2b-11e4-9ffb-a06162c13a84.png)
![screen shot 2015-05-14 at 11 19 20 am](https://cloud.githubusercontent.com/assets/88951/7636175/1a565fd8-fa2b-11e4-9b1e-5447b363b1e4.png)

**Comment by spxdcz** [comment]
Another potential config option:

* Autostart on login

**Comment by paulatbipsync** [comment]
all configuration is performed via the `defaults` commands listed on the main page (https://github.com/Bipsync/VagrantBar#configuration)
* Yosemite Dark Mode detection has been fixed in the latest release (1.19)
* Specifying a different Terminal is shown in the configuration table (see above) for example: `defaults write bipsync.Vagrant-Bar terminalAppName -string iTerm2`
* You can now display paths to machines as well as the IDs, (see configuration)
* Autostart on login is also mentioned on the main page (point 3 at https://github.com/Bipsync/VagrantBar#installation)
